//! DEVOLUTION//DECK — core library and Tauri plugin.

mod assistant;
mod audio;
mod commands;
mod deck;
mod models;
mod plugin_host;
mod project_io;
mod recovery;
mod show_control;

use commands::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let playback = audio::PlaybackHandle::new().expect("Failed to init audio playback");
    tauri::Builder::default()
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_shell::init())
        .manage(AppState {
            project: std::sync::Mutex::new(models::Project::default()),
            project_path: std::sync::Mutex::new(None),
            playback,
            recording: std::sync::Mutex::new(None),
            meter_source: std::sync::Mutex::new(None),
        })
        .invoke_handler(tauri::generate_handler![
            // Phase 1
            commands::project_new,
            commands::project_save,
            commands::project_open,
            commands::project_get,
            commands::project_update,
            commands::media_import_audio,
            commands::waveform_peaks,
            commands::track_add,
            commands::clip_place,
            commands::playback_play,
            commands::playback_play_arrangement,
            commands::playback_meters,
            commands::playback_stop,
            commands::playback_position_ms,
            commands::playback_is_playing,
            // Phase 2
            commands::playback_seek,
            commands::midi_clip_add,
            commands::midi_clip_update,
            commands::midi_clip_delete,
            commands::midi_clip_duplicate,
            commands::loop_region_set,
            commands::loop_region_clear,
            commands::track_set_type,
            commands::track_set_instrument,
            commands::recording_list_devices,
            commands::recording_start,
            commands::recording_stop,
            commands::recording_stop_to_timeline,
            commands::track_set_armed,
            commands::recording_is_active,
            // Phase 4
            commands::plugin_scan_default,
            commands::plugin_preflight,
            commands::plugin_scan_paths,
            commands::track_plugin_insert,
            commands::track_plugin_remove,
            commands::track_plugin_move,
            commands::track_plugin_set_bypass,
            commands::track_plugin_set_enabled,
            commands::track_plugin_set_parameter,
            commands::sidechain_route_add,
            commands::sidechain_route_update,
            commands::sidechain_route_remove,
            commands::stem_export_start,
            commands::mixdown_export_start,
            commands::track_freeze,
            commands::track_unfreeze,
            commands::track_render_in_place,
            commands::take_lane_add,
            commands::take_lane_clip_add,
            commands::comp_region_set,
            commands::comp_region_clear,
            commands::recovery_snapshot_save,
            commands::recovery_snapshot_list,
            commands::recovery_snapshot_restore,
            commands::monitoring_update,
            commands::autosave_interval_set,
            commands::shortcut_bindings_set,
            // Phase 5
            commands::assistant_harmony_generate,
            commands::assistant_asset_classify,
            commands::assistant_vocal_presets,
            commands::assistant_preset_apply,
            commands::dashboard_insights_generate,
            commands::dashboard_widget_state_update,
            commands::performance_mode_update,
            commands::performance_macro_upsert,
            commands::performance_macro_remove,
            commands::performance_macro_trigger,
            commands::scene_trigger_upsert,
            commands::scene_trigger_remove,
            commands::show_cue_upsert,
            commands::show_cue_remove,
            commands::show_cue_preview,
            commands::lighting_cue_binding_upsert,
            commands::lighting_cue_binding_remove,
            commands::visual_sync_update,
            commands::branding_update,
            // Phase 6
            commands::library_item_analyze_upsert,
            commands::library_item_update,
            commands::crate_upsert,
            commands::crate_remove,
            commands::crate_item_add,
            commands::crate_item_remove,
            commands::deck_load_track,
            commands::deck_set_playing,
            commands::deck_seek_position,
            commands::deck_turntable_nudge,
            commands::deck_turntable_scratch,
            commands::deck_turntable_configure,
            commands::deck_hot_cue_set,
            commands::deck_hot_cue_trigger,
            commands::deck_hot_cue_remove,
            commands::deck_loop_set,
            commands::deck_loop_clear,
            commands::deck_sync_update,
            commands::deck_sync_apply,
            commands::crossfader_update,
            commands::crossfader_bind_track,
            commands::sampler_slot_upsert,
            commands::sampler_slot_remove,
            commands::performance_pad_upsert,
            commands::performance_pad_remove,
            commands::performance_pad_trigger,
            commands::setlist_upsert,
            commands::setlist_remove,
            commands::setlist_set_active,
            commands::setlist_entry_mark_played,
            commands::show_trigger_upsert,
            commands::show_trigger_remove,
            commands::show_trigger_execute,
            commands::deck_event_binding_upsert,
            commands::deck_event_binding_remove,
            commands::deck_scene_link_upsert,
            commands::deck_scene_link_remove,
            commands::deck_scene_coordinate,
            // Phase 7
            commands::show_project_update,
            commands::dmx_bridge_update,
            commands::lighting_cue_upsert,
            commands::lighting_cue_remove,
            commands::lighting_cue_execute,
            commands::visual_cue_upsert,
            commands::visual_cue_remove,
            commands::visual_cue_execute,
            commands::cue_sequence_upsert,
            commands::cue_sequence_remove,
            commands::cue_sequence_start,
            commands::cue_sequence_stop,
            commands::cue_sequence_tick,
            commands::cue_trigger_upsert,
            commands::cue_trigger_remove,
            commands::cue_trigger_fire,
            commands::song_cue_map_upsert,
            commands::song_cue_map_remove,
            commands::song_cue_map_trigger,
            commands::device_binding_upsert,
            commands::device_binding_remove,
            commands::device_binding_test,
            commands::fallback_profile_upsert,
            commands::fallback_profile_remove,
            commands::fallback_profile_apply,
            commands::safety_blackout_set,
            commands::safety_panic,
            commands::safety_reset,
            commands::performance_dashboard_refresh,
            // Phase 8
            commands::navigation_update,
            commands::preferences_update,
            commands::device_profiles_refresh,
            commands::device_diagnostics_run,
            commands::compatibility_report_generate,
            commands::migration_plan_generate,
            commands::migration_plan_apply,
            commands::project_missing_media_scan,
            commands::project_missing_media_relink,
            commands::plugin_chain_preflight,
            commands::error_report_add,
            commands::error_report_ack,
            commands::error_report_list,
            commands::error_report_dispatch,
            commands::support_bundle_export,
            commands::performance_profile_capture,
            commands::release_config_update,
            commands::release_readiness_check,
            commands::onboarding_state_update,
            commands::system_health_snapshot,
        ])
        .run(tauri::generate_context!())
        .expect("error while running DEVOLUTION//DECK");
}
